Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -84,6 +84,36 @@ jobs:
           name: my-artifact
           path: my-artifact/
   
+  upload:
+    needs: package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: my-artifact
 
+      - name: Upload Node.js Artifact to Nexus
+        env:
+          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+          NEXUS_URL: ${{ secrets.NEXUS_URL }}
+        run: |
+          artifact_path=$(find ./my-artifact -name "*.tgz" | head -n 1)
+          if [ -z "$artifact_path" ]; then
+            echo "Error: No .tgz file found!"
+            exit 1
+          fi
+
+          if [ -z "$NEXUS_URL" ] || [ -z "$NEXUS_USERNAME" ] || [ -z "$NEXUS_PASSWORD" ]; then
+            echo "Error: Missing Nexus credentials or URL."
+            exit 1
+          fi
+
+          NEXUS_URL="${NEXUS_URL%/}"
+          curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
+            --upload-file "$artifact_path" \
+            "$NEXUS_URL/repository/MSS-NPM-PROJECT/$(basename "$artifact_path")"
+          echo "Upload complete."
 
   
