Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -84,32 +84,32 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-        
+
       - name: Download Artifact from GitHub Actions
         run: |
-         ARTIFACT_URL="https://github.com/gbaimy/nodejs-app-mss/actions/runs/12907530897/artifacts/2467541366"
-         OUTPUT_FILE="/home/runner/work/nodejs-app-mss/nodejs-app-mss/downloaded-artifact/my-artifact.zip"
-         curl -L -o "$OUTPUT_FILE" "$ARTIFACT_URL"
-         if [ ! -f "$OUTPUT_FILE" ]; then
-         echo "Error: Artifact download failed."
-         exit 1
-         else
-         echo "Artifact downloaded successfully: $OUTPUT_FILE"
-         fi
+          ARTIFACT_URL="https://github.com/gbaimy/nodejs-app-mss/actions/runs/12907530897/artifacts/2467541366"
+          OUTPUT_FILE="/home/runner/work/nodejs-app-mss/nodejs-app-mss/downloaded-artifact/my-artifact.zip"
+          curl -L -o "$OUTPUT_FILE" "$ARTIFACT_URL"
+          if [ ! -f "$OUTPUT_FILE" ]; then
+            echo "Error: Artifact download failed."
+            exit 1
+          else
+            echo "Artifact downloaded successfully: $OUTPUT_FILE"
+          fi
 
       - name: Upload Artifact to Nexus
         env:
-         NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-         NEXUS_URL: ${{ secrets.NEXUS_URL }}
-         run: |
+          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+          NEXUS_URL: ${{ secrets.NEXUS_URL }}
+        run: |
           if [ -z "$NEXUS_URL" ] || [ -z "$NEXUS_USERNAME" ] || [ -z "$NEXUS_PASSWORD" ]; then
-          echo "Error: Missing Nexus credentials or URL."
-          exit 1
-           fi
+            echo "Error: Missing Nexus credentials or URL."
+            exit 1
+          fi
 
-           NEXUS_URL="${NEXUS_URL%/}"
+          NEXUS_URL="${NEXUS_URL%/}"
           curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
-          --upload-file "$OUTPUT_FILE" \
-           "$NEXUS_URL/repository/mss-npm-project/$(basename "$OUTPUT_FILE")"
-           echo "Upload complete."
+            --upload-file "$OUTPUT_FILE" \
+            "$NEXUS_URL/repository/mss-npm-project/$(basename "$OUTPUT_FILE")"
+          echo "Upload complete."
