Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -46,7 +46,7 @@ jobs:
           sonar-scanner \
             -Dsonar.projectKey=mss-project \
             -Dsonar.sources=. \
-            -Dsonar.host.url=http://54.90.247.217:9000 \
+            -Dsonar.host.url=http://52.91.43.172:9000 \
             -Dsonar.login=$SONAR_TOKEN
 
   package:
@@ -58,32 +58,52 @@ jobs:
 
       - name: Create .tgz file
         run: |
-         mkdir -p /home/runner/work/nodejs-app-mss/nodejs-app-mss/temp
-         rsync -av --exclude=temp ./ /home/runner/work/nodejs-app-mss/nodejs-app-mss/temp/
-         tar -czf /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz -C /home/runner/work/nodejs-app-mss/nodejs-app-mss/temp .
-         echo "Generated .tgz file: /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz"
+          mkdir -p temp
+          rsync -av --exclude=temp ./ temp/
+          tar -czf /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz -C temp .
+          echo "Generated .tgz file: /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz"
 
       - name: Verify .tgz file
         run: |
-          if [ -f my-project.tgz ]; then
-            echo "Packaging successful: $(pwd)/my-project.tgz"
+          if [ -f /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz ]; then
+            echo "Packaging successful: /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz"
           else
             echo "Error: .tgz file not found!"
             exit 1
           fi
 
-      - name: Create artifact directory
-        run: mkdir -p my-artifact
-
-      - name: Move .tgz file to artifact directory
-        run: mv my-project.tgz my-artifact/
-
       - name: Save artifact for upload
         uses: actions/upload-artifact@v4
         with:
           name: my-artifact
-          path: my-artifact
+          path: /home/runner/work/nodejs-app-mss/nodejs-app-mss/my-project.tgz
 
+  retrieve_artifact:
+    needs: package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifact from GitHub Actions
+        run: |
+          ARTIFACT_URL="https://github.com/gbaimy/nodejs-app-mss/actions/runs/12906227635/artifacts/2467137616"
+          OUTPUT_DIR="/home/runner/work/nodejs-app-mss/nodejs-app-mss/downloaded-artifact"
+          mkdir -p $OUTPUT_DIR
+          curl -L -o $OUTPUT_DIR/my-artifact.zip $ARTIFACT_URL
+          echo "Artifact downloaded to: $OUTPUT_DIR/my-artifact.zip"
+
+      - name: Extract Artifact
+        run: |
+          unzip /home/runner/work/nodejs-app-mss/nodejs-app-mss/downloaded-artifact/my-artifact.zip -d /home/runner/work/nodejs-app-mss/nodejs-app-mss/extracted-artifact
+          echo "Artifact extracted to: /home/runner/work/nodejs-app-mss/nodejs-app-mss/extracted-artifact"
+
+      - name: Locate .tgz file in extracted artifact
+        run: |
+          artifact_path=$(find /home/runner/work/nodejs-app-mss/nodejs-app-mss/extracted-artifact -name "*.tgz" | head -n 1)
+          if [ -z "$artifact_path" ]; then
+            echo "Error: No .tgz file found in extracted artifact directory."
+            exit 1
+          else
+            echo "Found .tgz file: $artifact_path"
+          fi
   upload_artifact:
     needs: package
     runs-on: ubuntu-latest
@@ -94,9 +114,9 @@ jobs:
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
           NEXUS_URL: ${{ secrets.NEXUS_URL }}
         run: |
-          artifact_path=$(find /home/runner/work/<repository>/<repository>/my-artifact.zip "*.tgz" | head -n 1)
+          artifact_path=$(find /home/runner/work/nodejs-app-mss/nodejs-app-mss/extracted-artifact -name  "*.tgz" | head -n 1)
           if [ -z "$artifact_path" ]; then
-            echo "Error: No .tgz file found in /home/runner/work/<repository>/<repository>/my-artifact.zip"
+            echo "Error: No .tgz file found in /home/runner/work/nodejs-app-mss/nodejs-app-mss/extracted-artifact -name "
             exit 1
           else
             echo "Found artifact: $artifact_path"
