Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -51,38 +51,36 @@ jobs:
             -Dsonar.host.url=http://54.226.144.119:9000\
             -Dsonar.login=$SONAR_TOKEN
             
-      - name: Package code into .tgz
+      - name: Prepare files for packaging
         run: |
-         mkdir -p temp
-         mkdir -p /var/lib/jenkins/myrepodemos/mydemos/nodejs-app-mss/nodejs-app-mss/
-         tar -czf /var/lib/jenkins/myrepodemos/mydemos/nodejs-app-mss/nodejs-app-mss/my-project.tgz -C temp .
-         echo "Generated artifact: /var/lib/jenkins/myrepodemos/mydemos/nodejs-app-mss/nodejs-app-mss/my-project.tgz"
+         mkdir temp
+         cp -r ./* temp/
+         echo "All files copied to temporary directory."
+         
+      - name: Create .tgz file
+        run: |
+         tar -czf my-project.tgz -C temp .
+         echo "Generated artifact: $(pwd)/my-project.tgz"
           
       - name: Verify .tgz file
         run: |
-         if [ -f my-project.tgz ]; then
-          echo "Packaging successful."
-         else
-          echo "Failed to create .tgz file!"
+         ARTIFACT_DIR="."
+         ARTIFACT=$(ls $ARTIFACT_DIR/*.tgz 2>/dev/null || echo "")
+         if [ -z "$ARTIFACT" ]; then
+          echo "Error: No .tgz file found in $ARTIFACT_DIR. Please check the build process."
           exit 1
          fi
+         echo "Found artifact: $ARTIFACT"
          
       - name: Upload Node.js Artifact to Nexus
         env:
-          NEXUS_URL: ${{ secrets.NEXUS_URL }}
           NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+          NEXUS_URL: ${{ secrets.NEXUS_URL }}
         run: |
-           ARTIFACT_DIR="/var/lib/jenkins/myrepodemos/mydemos/nodejs-app-mss/nodejs-app-mss/*.tgz*"
-           ARTIFACT=$(ls $ARTIFACT_DIR/*.tgz 2>/dev/null || echo "")
-           if [ -z "$ARTIFACT" ]; then
-            echo "Error: No .tgz file found in $ARTIFACT_DIR. Please check the build process."
-            exit 1
-           fi
-           echo "Found artifact: $ARTIFACT"
-           curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD \ --upload-file "$ARTIFACT" \"$NEXUS_URL/repository/nodejs-app-mss/$(basename $ARTIFACT)"
-           echo "Upload complete."
-
+         curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file "$ARTIFACT" "$NEXUS_URL/repository/nodejs-app-mss/$(basename $ARTIFACT)"
+         echo "Upload complete."
+      
       - name: Run Node.js App
         run: |
           npm start
