Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -88,32 +88,40 @@ jobs:
    needs: package
    runs-on: ubuntu-latest
    steps:
-    - name: Download artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: my-artifact
+   - name: Unzip artifact from specified path
+     run: |
+      artifact_path=$(find /home/runner/work/nodejs-app-mss/nodejs-app-mss -name "*.zip" | head -n 1)
+      if [ -z "$artifact_path" ]; then
+      echo "Error: No .zip file found in /home/runner/work/nodejs-app-mss/nodejs-app-mss"
+      exit 1
+      fi
+      echo "Found artifact to unzip: $artifact_path"
+      mkdir -p extracted-artifact
+      unzip "$artifact_path" -d extracted-artifact
+      echo "Artifact extracted to: $(pwd)/extracted-artifact"
 
-    - name: Upload Node.js Artifact to Nexus
-      env:
-        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-        NEXUS_URL: ${{ secrets.NEXUS_URL }}
-      run: |
-        artifact_path=$(find /home/runner/work/nodejs-app-mss/nodejs-app-mss -name "*.tgz" | head -n 1)
-        if [ -z "$artifact_path" ]; then
-          echo "Error: No .tgz file found in /home/runner/work/nodejs-app-mss/nodejs-app-mss"
-          exit 1
-        else
-          echo "Found artifact: $artifact_path"
-        fi
+   - name: Upload Node.js Artifact to Nexus
+   env:
+     NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+     NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+     NEXUS_URL: ${{ secrets.NEXUS_URL }}
+     run: |
+      artifact_path=$(find ./extracted-artifact -name "*.tgz" | head -n 1)
+      if [ -z "$artifact_path" ]; then
+       echo "Error: No .tgz file found in extracted-artifact directory."
+       exit 1
+      else
+      echo "Found artifact: $artifact_path"
+      fi
 
-        if [ -z "$NEXUS_URL" ] || [ -z "$NEXUS_USERNAME" ] || [ -z "$NEXUS_PASSWORD" ]; then
-          echo "Error: Missing Nexus credentials or URL."
-          exit 1
-        fi
+      if [ -z "$NEXUS_URL" ] || [ -z "$NEXUS_USERNAME" ] || [ -z "$NEXUS_PASSWORD" ]; then
+      echo "Error: Missing Nexus credentials or URL."
+      exit 1
+      fi
 
-        NEXUS_URL="${NEXUS_URL%/}"
-        curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
-          --upload-file "$artifact_path" \
-          "$NEXUS_URL/repository/MSS-NPM-PROJECT/$(basename "$artifact_path")"
-        echo "Upload complete."
+      NEXUS_URL="${NEXUS_URL%/}"
+      curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
+      --upload-file "$artifact_path" \
+      "$NEXUS_URL/repository/MSS-NPM-PROJECT/$(basename "$artifact_path")"
+      echo "Upload complete."
+      
