Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -104,11 +104,16 @@ jobs:
          exit 1
           fi
           
+          if [ ! -f "$artifact_path" ]; then
+          echo "Error: Artifact not found at $artifact_path"
+          exit 1
+          fi
+ 
          NEXUS_URL="${NEXUS_URL%}"
          curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
-         --upload-file "$artifact_path" \
-         "$NEXUS_URL $(basename "$artifact_path")"\
-         echo "Upload complete."
+             --upload-file "$artifact_path" \
+             "$NEXUS_URL/repository/MSS-NPM-PROJECT/ $(basename "$artifact_path")"
+              echo "Upload complete."
 
       - name: Run Application and Validate
         run: |
